In [ ]:
# Read all answers of given questions.

In [ ]:
# Theoretical Questions

In [ ]:
#Q1)Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
# Ans. NumPy enhances Python's capabilities for scientific computing and data analysis by providing efficient, multidimensional array objects (ndarrays) and 
# functions for performing high-performance numerical operations. It supports element-wise operations, matrix manipulations, and complex mathematical functions, making 
# it much faster than standard Python lists for large datasets. NumPy also integrates well with other libraries, enabling seamless data processing and analysis workflows. 
# Its array-based computing reduces memory usage and computational time, making it a fundamental tool for data science and scientific applications.

In [2]:
#Q2) Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
# Ans. In NumPy, np.mean() and np.average() both calculate the average of an array, but they have key differences:
# mean():- Calculate the simple arethmatic, treating all elements equally.
# average():- Allows specifying weights, so some elements contribute more to the average than others.
# When to use:
# np.mean() is used when all elements are equally important.
# np.average() is useful when you need a weighted average, where certain values have more significance.
# Example:-
import numpy as np
arr=np.array([1,2,3,4])
mean_array=np.mean(arr)

weights = np.array([1, 2, 3, 4])
average_array = np.average(arr, weights=weights)
print(mean_array)
print(average_array)

2.5
3.0


In [4]:
#Q3) Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
# In NumPy, you can reverse arrays along different axes using slicing or the np.flip() function. These methods allow for reversing arrays in different dimensions 
# (1D, 2D, etc.).

# 1. Reversing a 1D Array
# Method 1: Using slicing: [::-1] will reverse the array.
# Method 2: Using np.flip(): This function can flip the array along a specified axis.
# Example (1D array):

# 1-D array
arr_1d=np.array([1,2,3,4,5])
# using slicing
reverse_1d_slice= arr_1d[::-1]

# using flip()
reverse_1d_flip=np.flip(arr_1d)

print(reverse_1d_slice)
print(reverse_1d_flip)

[5 4 3 2 1]
[5 4 3 2 1]


In [8]:
# 2. Reversing a 2D Array
# For 2D arrays, you can reverse rows, columns, or both.

# Method 1: Using slicing:

# [::-1, :] reverses rows.
# [:, ::-1] reverses columns.
# [::-1, ::-1] reverses both rows and columns.
# Method 2: Using np.flip():

# np.flip(arr, axis=0) reverses along rows.
# np.flip(arr, axis=1) reverses along columns.
# np.flip(arr) reverses both rows and columns.
# Example (2D array):
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Reverse rows (along axis 0)
reversed_rows_slice = arr_2d[::-1, :]
reversed_rows_flip = np.flip(arr_2d, axis=0)

# Reverse columns (along axis 1)
reversed_cols_slice = arr_2d[:, ::-1]
reversed_cols_flip = np.flip(arr_2d, axis=1)

# Reverse both rows and columns
reversed_both_slice = arr_2d[::-1, ::-1]
reversed_both_flip = np.flip(arr_2d)

print(reversed_rows_slice)
print(reversed_cols_slice)

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [10]:
# Q4) How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
# Creating an array
arr = np.array([1, 2, 3])

# Determining the data type
print(arr.dtype)

int32


In [ ]:
# Importance of Data Types in Memory Management and Performance:
# Memory Efficiency: NumPy arrays use fixed-size data types, unlike Python lists, which store objects. This allows for more compact memory storage, especially when using 
# smaller data types (e.g., int8 vs int64), reducing the memory footprint for large datasets.

# Performance: Fixed-size data types allow NumPy to perform operations in contiguous memory blocks, leading to faster computation compared to dynamically typed Python 
# lists. Operations on NumPy arrays are highly optimized for performance, especially in large-scale numerical tasks.

# Selecting the appropriate data type is essential for balancing memory usage and computational speed.

In [12]:
# Q5) Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
# An ndarray (N-dimensional array) in NumPy is a multidimensional, homogeneous data structure used for numerical computations. It is the core data type in NumPy.

# ### Key Features of ndarrays:
# 1. Homogeneous: All elements in the array must be of the same data type (e.g., `int`, `float`).
# 2. Multidimensional: Supports arrays of any dimension (1D, 2D, 3D, etc.), allowing for complex data structures like matrices.
# 3. Fixed Size: The size of an ndarray is fixed at the time of creation, making them more memory efficient.
# 4. Vectorized Operations: Supports element-wise operations and broadcasting, making computations faster.
# 5. Efficient Memory Layout: Data is stored in contiguous memory blocks, allowing for faster access and manipulation.

# ### Differences from Python Lists:
# - Data Type: Lists can contain mixed data types, while ndarrays are homogeneous.
# - Performance: ndarrays are faster and more memory-efficient due to fixed size and contiguous memory storage.
# - Operations: ndarrays support vectorized operations (e.g., element-wise addition), whereas lists require loops or manual iteration for such operations.

# In short, ndarrays are optimized for numerical operations, making them superior for scientific computing compared to Python lists.

# Example:
import numpy as np

# Create a 2D ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
int32


In [3]:
#Q6)Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
# Ans. NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:

# 1. Memory Efficiency: NumPy arrays store data in contiguous blocks of memory, allowing for more efficient storage and access compared to Python lists, which are arrays 
# of pointers to objects. This reduces memory overhead.

# 2. Vectorized Operations: NumPy supports vectorized operations, meaning operations are applied element-wise, avoiding the need for explicit loops in Python. This leads 
# to faster execution.

# 3. Optimized C Backend: NumPy is implemented in C, and many of its operations are highly optimized for speed, whereas Python lists rely on slower Python loops.

# 4. Data Type Homogeneity: NumPy arrays require that all elements be of the same data type, allowing for faster computations. Python lists can store heterogeneous data, 
# adding overhead.
import numpy as np
import time

# Python list
size = 10**6
list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
result_list = [x + y for x, y in zip(list1, list2)]
print("List time:", time.time() - start_time)

# NumPy array
array1 = np.arange(size)
array2 = np.arange(size)

start_time = time.time()
result_array = array1 + array2
print("NumPy time:", time.time() - start_time)

List time: 0.12057614326477051
NumPy time: 0.0


In [4]:
# Q7) Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
# Ans. In NumPy, vstack() and hstack() are used to stack arrays vertically and horizontally, respectively.

# 1. vstack(): Stacks arrays vertically (row-wise), aligning them along columns.
# It requires arrays to have the same number of columns.
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result_vstack = np.vstack((a, b))
print(result_vstack)

# 2. hstack(): Stacks arrays horizontally (column-wise), aligning them along rows.
# It requires arrays to have the same number of rows.
result_hstack = np.hstack((a, b))
print(result_hstack)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [5]:
# Q8)Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
# Ans. In NumPy, the methods fliplr() and flipud() are used to flip arrays along specific axes, but they operate differently depending on the dimension:

# 1. fliplr() (Flip Left to Right):
# Effect: It flips the array horizontally (left to right) along the columns.
# Applicable: This works only on 2D arrays or higher. It reverses the order of columns.
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
result_fliplr = np.fliplr(arr)
print(result_fliplr)

# 2. flipud() (Flip Up to Down):
# Effect: It flips the array vertically (upside down) along the rows.
# Applicable: This works on arrays of any dimension (1D, 2D, or higher). It reverses the order of rows.
result_flipud = np.flipud(arr)
print(result_flipud)

[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [1]:
# Q9) Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
# Ans. The array_split() method in NumPy splits an array into multiple sub-arrays along a specified axis. It's particularly useful when you want to divide an array into 
# a certain number of parts, even if those parts are not of equal size.

# Handling Uneven Splits:
# If the array cannot be evenly divided by the specified number of sections, array_split() handles this by creating sub-arrays where some parts may have more elements than others. Specifically:

# It distributes the remainder among the earlier sections, making them slightly larger.
# For example, if you split an array of 10 elements into 3 parts, the result might be arrays of sizes [4, 3, 3] instead of equal sizes.
# This behavior allows flexibility in splitting arrays that do not have a size divisible by the number of desired splits.
import numpy as np

# Create an array of 10 elements
arr = np.arange(10)

# Split the array into 3 parts
splits = np.array_split(arr, 3)

for i, split in enumerate(splits):
    print(f"Split {i}: {split}")

Split 0: [0 1 2 3]
Split 1: [4 5 6]
Split 2: [7 8 9]


In [ ]:
# Q10) Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
Ans. In NumPy, vectorization refers to performing operations on entire arrays (vectors) without the need for explicit loops, leveraging highly optimized C code 
under the hood. This makes operations much faster than traditional loops in Python.

Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. Instead of reshaping data manually, broadcasting automatically 
expands smaller arrays to match the shape of larger ones, enabling element-wise operations without needing explicit looping.

Both vectorization and broadcasting contribute to efficient array operations by reducing the overhead of Python loops and minimizing memory usage, making numerical 
computations faster and more efficient.

In [ ]:
# Practical Questions

In [2]:
#Q1)Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
import numpy as np
ar=np.random.randint(1,100,(3,3))
print(ar)
print('__________')
print(ar.T)

[[ 3 41  9]
 [18 46 42]
 [98 90 99]]
__________
[[ 3 18 98]
 [41 46 90]
 [ 9 42 99]]


In [42]:
#Q2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
ar=np.array([1,2,3,4,5,6,7,8,9,10])
print('Original array')
print(ar)
print('2x5 array')
print(ar.reshape(2,5))
print('5x2 array')
ar.reshape(5,2)

Original array
[ 1  2  3  4  5  6  7  8  9 10]
2x5 array
5x2 array


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [34]:
#Q3)Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
original_array=np.random.rand(4,4)
er_array=np.pad(original_array, pad_width=1, mode='constant',constant_values=0)
print('Original array: ', original_array)
print('border_array: ', border_array)
brd=border_array.reshape(4,4)
brd

Original array:  [[0.58682536 0.90774351 0.66345213 0.66724066]
 [0.27963705 0.17923341 0.36794886 0.69826036]
 [0.18012014 0.06912946 0.36498438 0.85857219]
 [0.44811167 0.94632111 0.16626576 0.03369231]]
border_array:  [[0.         0.87055374 0.88747173 0.33373203]
 [0.47202431 0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]


array([[0.        , 0.87055374, 0.88747173, 0.33373203],
       [0.47202431, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [36]:
# Q4)Using NumPy, create an array of integers from 10 to 60 with a step of 5.
array=np.arange(10,60)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59]


In [12]:
# Q5)Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
x=np.array(['python','numpy','pandas'])
print(x)
upper_case=np.char.upper(x)
print(upper_case)
lower_case=np.char.lower(x)
print(lower_case)
title_case=np.char.title(x)
print(title_case)
capitalize_case=np.char.capitalize(x)
print(capitalize_case)

['python' 'numpy' 'pandas']
['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']
['Python' 'Numpy' 'Pandas']


In [16]:
# Q6)Generate a NumPy array of words. Insert a space between each character of every word in the array.
x=np.array(['python','numpy','pandas'])
print('Original array: ',x)
r=np.char.join(' ', x)
print(r)

Original array:  ['python' 'numpy' 'pandas']
['p y t h o n' 'n u m p y' 'p a n d a s']


In [37]:
# Q7)Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
arr1=np.random.rand(2,2)
print(arr1)
arr2=np.random.rand(2,2)
print(arr2)
# add two 2-D array
add_array=np.add(arr1,arr2)
print('addition of two array: ',add_array)
# subtract two 2-D array
substraction_array=np.subtract(arr1,arr2)
print('subtraction of two array: ',substraction_array)
# multiplication 2-D array
multiplication_array=np.multiply(arr1,arr2)
print('multiplication of two array: ',multiplication_array)
# division 2-D array
division_array=np.divide(arr1,arr2)
print('division of two array: ',division_array)

[[0.08912359 0.04036108]
 [0.68156231 0.80734379]]
[[0.44611458 0.97187697]
 [0.4133955  0.07559208]]
addition of two array:  [[0.53523817 1.01223806]
 [1.09495781 0.88293587]]
subtraction of two array:  [[-0.35699099 -0.93151589]
 [ 0.2681668   0.7317517 ]]
multiplication of two array:  [[0.03975933 0.03922601]
 [0.28175479 0.0610288 ]]
division of two array:  [[ 0.19977736  0.041529  ]
 [ 1.64869308 10.68026882]]


In [51]:
# Q8)Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
x=np.eye(5,5)
print(x)
y=np.diag(x)
print(y)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1. 1. 1. 1. 1.]


In [53]:
# Q9)Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Find and display all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

random_integers, prime_numbers

(array([470, 653, 135,  41, 736, 143, 494, 275, 395, 713, 126, 382, 941,
        345, 755, 220, 425,  11, 160, 416,  91, 824, 425, 687, 167, 416,
        431, 435, 216, 659, 749, 808, 621, 646, 780, 229, 686, 987, 527,
        533, 901, 222, 676, 100, 812, 855, 291, 538, 882, 947,   1, 945,
        769, 252, 903, 341,  85, 489, 598, 810, 777,   6, 323, 428, 755,
        232, 204, 813, 489, 430, 976, 989,  15, 993, 862, 236,  29, 869,
        120, 135, 640, 331,  99, 622, 758, 704, 189, 932, 112, 395, 734,
        643,  68, 411,  55, 667, 768, 365, 918, 803]),
 [653, 41, 941, 11, 167, 431, 659, 229, 947, 769, 29, 331, 643])